import { DM_Sans } from "next/font/google";
import "./globals.css";
import "./style.css"

import Navigation from "./components/navigation";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} antialiased`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
