import { DM_Sans } from "next/font/google";
import "./globals.css";
import "./style.css";

import Navigation from "./components/navigation";
import Footer from "./components/footer";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Photosnap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
